rebuild and bump from fedora 20 to fedora 21
Note: git-remote-hg obsoletes git-hg as of
https://bugzilla.redhat.com/show_bug.cgi?id=1170008
and resolves failure to install git-hg:

    Error: Package: git-hg-2.1.0-2.fc21.noarch (fedora)
    Requires: git = 2.1.0-2.fc21
    Available: git-2.1.0-2.fc21.x86_64 (fedora)
               git = 2.1.0-2.fc21
    Installing: git-2.1.0-4.fc21.x86_64 (updates)
               git = 2.1.0-4.fc21

See also https://admin.fedoraproject.org/updates/git-2.1.0-4.fc21